go.property("object_url", msg.url())

local render3d = require("scene3d.render.render3d")

local HAS_FIXED_UPDATE = render3d.engine_version(1, 3, 1)

function init(self)
    self.angle = 0
end

function final(self)
end

local function update_animation(self, dt)
    self.angle = self.angle + 60 * dt

    -- DEBUG
    -- print(render3d.frame_num .. string.format(": fixed update, angle is %.02f", self.angle))

    go.set(self.object_url, "euler.y", self.angle)
end

function update(self, dt)
    if not HAS_FIXED_UPDATE then
        update_animation(self, dt)
    end
end

function fixed_update(self, dt)
    update_animation(self, dt)
end

function on_message(self, message_id, message, sender)
end

function on_input(self, action_id, action)
end
