go.property("acquire_input_focus", true)
go.property("key_forward", hash("key_w"))
go.property("key_backward", hash("key_s"))
go.property("key_left", hash("key_a"))
go.property("key_right", hash("key_d"))

local render3d = require("scene3d.render.render3d")

local HAS_FIXED_UPDATE = render3d.engine_version(1, 3, 1)

function init(self)
    if self.acquire_input_focus then
        msg.post(".", hash("acquire_input_focus"))
    end
end

function final(self)
end

local function do_fixed_update(self, dt)
    
end

function update(self, dt)
    if not HAS_FIXED_UPDATE then
        do_fixed_update(self, dt)
    end
end

function fixed_update(self, dt)
    do_fixed_update(self, dt)
end

function on_message(self, message_id, message, sender)
end

function on_input(self, action_id, action)
    if action_id == self.key_forward then
        self.input_key_forward = not action.released
    elseif action_id == self.key_backward then
        self.input_key_backward = not action.released
    elseif action_id == self.key_left then
        self.input_key_left = not action.released
    elseif action_id == self.key_right then
        self.input_key_right = not action.released
    end
end
