local render3d = require("scene3d.render.render3d")

go.property("acquire_input_focus", true)

function init(self)
    print("basic_3d_main: init()")

    if self.acquire_input_focus then
        msg.post(".", hash("acquire_input_focus"))
    end
end

function final(self)
end

function update(self, dt)
end

function on_message(self, message_id, message, sender)
end

function on_input(self, action_id, action)
end
